In [2]:
import numpy as np

In [40]:
#Question 1
#1.	Create a numpy array of size 10, filled with zeros
A=np.zeros(10)
A

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
#Question 2
#2.	Create a numpy array with values ranging from 10 to 49 and set its datatype to float
a = np.arange(10,50)
b = np.array((a), dtype=float)
print(b)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


In [62]:
#Question 3
#3.	Create a numpy matrix of 2*2 integers, filled with ones

x= np.ones((2,2), dtype=int)

print(x)

[[1 1]
 [1 1]]


In [93]:
#Question 4
#4.	Create a numpy matrix of 3*2 float numbers, filled with ones.

z= np.ones((3,2), dtype=int)

print(z)
z.shape

[[1 1]
 [1 1]
 [1 1]]


(3, 2)

In [ ]:
#5.	Given the X numpy array, create a new numpy array with the same shape and type as X, 
#filled with ones. (#hint: search the function np.ones_like( ) )

In [94]:
x = (np.ones_like(z,int))
print("Matrix b : \n", x)

Matrix b : 
 [[1 1]
 [1 1]
 [1 1]]


In [57]:
#6.	Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, 
#filled with zeros. (hint: similar function as above exists for zeros as well)

u=np.zeros((3,2))
u

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [95]:
#7.	Create a numpy matrix of 4*4 integers, filled with fives
x=np.full((4,4),5)
x

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [75]:
#8.	Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
x=np.full_like(x,7)
x

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [97]:
#9.	Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
x=np.eye((3))
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [126]:
#10.	Create a numpy array, filled with 3 random integer values between 1 and 10.
y=np.random.randint(1,11, size=3)
y

array([6, 3, 9])

In [122]:
#11.	Create a 3*3*3 numpy matrix, filled with random float values.
A = np.random.randint(100, size=(3, 3, 3))
arr = A.astype('float64') 
  
# Print the array after changing 
# the data type 
print(arr) 

[[[48. 46. 79.]
  [39. 24. 94.]
  [22. 68. 20.]]

 [[99. 97. 90.]
  [56. 93. 14.]
  [21. 47.  9.]]

 [[30. 58. 92.]
  [76. 19. 41.]
  [70. 98. 15.]]]


In [145]:
#12.	Create a numpy array with numbers from 1 to 10
u = np.arange(1,11)
print(u)

[ 1  2  3  4  5  6  7  8  9 10]


In [151]:
#13.	Create a numpy array with the odd numbers between 1 to 10
u1 = np.arange(1,11,2)

# 2nd method
# l=np.where(u%2==0)

print(u1)

[1 3 5 7 9]


In [157]:
# 14.	Create a numpy array with numbers from 1 to 10, in descending order
u2 = np.arange(1,11)

u3 = u2[::-1]
print(u3)

[10  9  8  7  6  5  4  3  2  1]


In [167]:
#15.	Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

t = np.arange(9).reshape(3, 3)
print(t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
#Array indexing:
#1.	Given the X numpy array, show its first element

x = np.array(['A','B','C','D','E'])
print("First Element :", x[0])


First Element : A


In [36]:
#2.	Given the X numpy array, show its last element
print("First Element :", x[-1])

First Element : E


In [170]:
#3.	Given the X numpy array, show its first three elements
print("first three elements :", x[0:3])

first three elements : ['A' 'B' 'C']


In [204]:
#4.	Given the X numpy array, show all middle elements
mid = len(x) // 2

# Show all middle elements
mid_elements = x[mid]
print(mid_elements)

C


In [205]:
#5.	Given the X numpy array, show the elements in reverse position.
y1=x[::-1]
print(y1)

['E' 'D' 'C' 'B' 'A']


In [215]:
#6.	Given the X numpy array, show the elements in an odd position.
y2= x[1::2]
print(y2)

['B' 'D']


In [221]:
#7.	Given the X numpy matrix, show the first row’s elements.
x = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
x[0]

array([1, 2, 3, 4])

In [222]:
# 8.	Given the X numpy matrix, show the last row elements.
x[-1]

array([13, 14, 15, 16])

In [225]:
#9.	Given the X numpy matrix, show the first element on first row
x[0][0]

1

In [265]:
#10.	Given the X numpy matrix, show the last element on last row.
x[-1][-1]

16

In [262]:
#11.	Given the X numpy matrix, show the first two elements on the first two rows.
x = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
x4= x[:2, :2]
print(x4)

[[1 2]
 [5 6]]


In [264]:
#12.	Given the X numpy matrix, show the last two elements on the last two rows
x6= x[-2:, -2:]
print(x6)

[[11 12]
 [15 16]]


In [241]:
#Array manipulation
#1.	Convert the given integer numpy array to float 
x= np.array([-5, -3, 0, 10, 40])
y = np.asfarray(x)
print(y)

[-5. -3.  0. 10. 40.]


In [244]:
#2.	Reverse the given numpy array (first element becomes last) through indexing
x[::-1]

array([40, 10,  0, -3, -5])

In [250]:
#3.	Given the X numpy array, set the fifth element equal to 1
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [254]:
#4.	Given the X numpy matrix, change the last row with all 1
x = np.array([[1,   2,  3,  4],
                [5,   6,  7,  8],
                [9,  10, 11, 12],
                [13, 14, 15, 16]             
             
             ])

x[3] = 1
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


In [258]:
#	5.	Given the X numpy matrix, add 5 to every element
x+=5
print(x)

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [ 6  6  6  6]]
